// A list of cybersecurity facts and stats for display in CyberGuard
const cyberFacts = [
    "Over 90% of cyber attacks start with a phishing email.",
    "Ransomware attacks increased by 150% in 2020.",
    "Weak passwords are responsible for 81% of hacking-related breaches.",
    "The average cost of a data breach in 2023 was $4.45 million.",
    "More than 300,000 new malware samples are created every day.",
    "IoT devices are attacked within 5 minutes of connecting to the internet.",
    "Only 5% of company folders are properly protected.",
    "Cybercrime is projected to cost the world $10.5 trillion annually by 2025.",
    "Mobile malware attacks increased by 54% in 2022.",
    "Human error accounts for 95% of cybersecurity breaches.",
    "60% of small businesses close within six months of a cyber attack.",
    "The global cybersecurity workforce shortage is over 4 million professionals.",
    "Phishing attacks account for 36% of all data breaches.",
    "Over 70% of organizations lack a cybersecurity incident response plan.",
    "Social engineering attacks exploit 98% of human vulnerabilities.",
    "The average time to detect a data breach is 287 days.",
    "Cryptojacking attacks rose by 23% in 2023.",
    "Only 38% of organizations have a cybersecurity awareness training program.",
    "DDoS attacks increased by 200% during the COVID-19 pandemic.",
    "93% of malware is polymorphic, changing to evade detection.",
    "Cloud-based attacks grew by 48% in 2022.",
    "Over 80% of organizations have experienced a cloud security breach.",
    "The dark web sells stolen data for as little as $1 per record.",
    "62% of businesses experienced a phishing attack in 2023.",
    "Unpatched software vulnerabilities account for 60% of breaches.",
    "The healthcare sector faces the highest data breach costs at $10.1 million.",
    "Over 50% of phishing emails impersonate trusted brands.",
    "Zero-day exploits were used in 40% of advanced attacks in 2023.",
    "Only 14% of organizations use multi-factor authentication universally.",
    "Cyber attacks targeting APIs increased by 681% from 2021 to 2023.",
    "95% of cybersecurity issues can be traced to misconfigured systems.",
    "Remote work increased cyber risks by 67% since 2020.",
    "The average ransomware payment in 2023 was $1.54 million.",
    "43% of cyber attacks target small and medium-sized businesses.",
    "Over 70% of malware is delivered via email attachments.",
    "Insider threats cause 34% of data breaches.",
    "Only 25% of organizations encrypt sensitive data at rest.",
    "Supply chain attacks grew by 42% in 2022.",
    "The average cost of a phishing attack is $1.6 million.",
    "66% of organizations lack real-time threat detection capabilities.",
    "Mobile banking malware grew by 80% in 2023.",
    "Over 85% of breaches involve stolen or compromised credentials.",
    "The global cybersecurity market is expected to reach $376 billion by 2029.",
    "Only 10% of IoT devices have robust security features.",
    "Business email compromise (BEC) attacks cost $2.7 billion in 2023.",
    "94% of organizations have unsecured cloud storage exposed online.",
    "AI-powered attacks increased by 30% in 2023.",
    "Only 20% of companies regularly update their cybersecurity policies.",
    "The average cost of downtime from a cyber attack is $1.2 million per hour.",
    "Over 60% of ransomware attacks now involve data exfiltration.",
    "Only 30% of organizations conduct regular penetration testing.",
    "Cyber attacks on critical infrastructure rose by 140% in 2023.",
    "78% of organizations lack confidence in their cybersecurity posture.",
    "The average lifespan of a malware sample is less than 24 hours.",
    "Over 50% of phishing sites use HTTPS to appear legitimate.",
    "Only 15% of organizations have a dedicated cybersecurity budget.",
    "Credential stuffing attacks succeed in 0.8% of attempts.",
    "The financial sector faces 300 times more attacks than other industries.",
    "Only 12% of employees follow cybersecurity best practices consistently.",
    "Ransomware-as-a-service (RaaS) grew by 112% in 2023.",
    "Over 88% of organizations have outdated software vulnerabilities.",
    "The average time to patch a critical vulnerability is 60 days.",
    "Only 22% of organizations have a zero-trust architecture in place.",
    "Cyber attacks on gaming platforms increased by 340% in 2022.",
    "Over 75% of organizations lack endpoint security for remote devices.",
    "The dark web hosts over 15,000 sites selling hacking tools.",
    "Only 18% of organizations have a cyber insurance policy.",
    "Malware targeting macOS increased by 165% in 2023.",
    "Over 90% of successful attacks exploit known vulnerabilities.",
    "The average cost of a DDoS attack is $120,000 per incident.",
    "Only 35% of organizations back up data daily.",
    "Cyber attacks on schools increased by 75% in 2023.",
    "Over 80% of organizations fail to secure third-party vendors.",
    "The average phishing email click rate is 17.8%.",
    "Only 27% of organizations use AI for threat detection.",
    "Ransomware attacks encrypt data in under 10 minutes on average.",
    "Over 65% of organizations lack a cybersecurity culture.",
    "The average cost of a BEC attack is $5.96 million.",
    "Only 16% of organizations have a secure software development lifecycle.",
    "Cyber attacks on retail increased by 88% in 2023.",
    "Over 70% of organizations have shadow IT vulnerabilities.",
    "The average time to respond to a breach is 49 days.",
    "Only 19% of organizations use threat intelligence platforms.",
    "Malware targeting Linux systems grew by 645% in 2023.",
    "Over 85% of organizations have experienced a social engineering attack.",
    "The average cost of a ransomware attack is $4.54 million.",
    "Only 13% of organizations have a CISO in place.",
    "Cyber attacks on energy sectors rose by 380% in 2023.",
    "Over 60% of organizations lack a disaster recovery plan.",
    "The average success rate of phishing simulations is 11%.",
    "Only 24% of organizations monitor their dark web exposure.",
    "Cyber attacks targeting 5G networks increased by 200% in 2023.",
    "Over 90% of organizations have misconfigured firewalls.",
    "The average cost of insider threat incidents is $15.4 million.",
    "Only 17% of organizations conduct regular security audits."
  ];
export default cyberFacts;
